# Generated by Django 4.2.11 on 2024-05-17 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producer', '0004_project_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
