# Generated by Django 4.2.11 on 2024-05-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0005_categoryproject_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproject',
            name='budget',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
