# Generated by Django 4.2.11 on 2024-05-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0006_alter_categoryproject_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('receipt_image', models.ImageField(upload_to='')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.categoryproject')),
            ],
        ),
    ]
