# Generated by Django 4.2.11 on 2024-06-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0008_task_item_id'),
        ('producer', '0007_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
        migrations.AddField(
            model_name='expense',
            name='shop_list_item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks_app.shoplistitem'),
            preserve_default=False,
        ),
    ]
