# Generated by Django 4.2.11 on 2024-06-03 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DEFAULT', 'По умолчанию'), ('ACCOUNTANT', 'Бухгалтер'), ('LINE_PRODUCER', 'Линейный продюсер')], default='DEFAULT', max_length=20, verbose_name='Имя Группы')),
                ('user', models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
