# Generated by Django 4.2.11 on 2024-06-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(choices=[('DEFAULT', 'По умолчанию'), ('ACCOUNTANT', 'Бухгалтер'), ('LINE_PRODUCER', 'Линейный продюсер'), ('PRODUCER', 'Продюсер'), ('EXECUTIVE_PRODUCER', 'Исполнительный продюсер'), ('BUYER', 'Закупщик')], default='DEFAULT', max_length=20, verbose_name='Имя Группы'),
        ),
    ]
