# Generated by Django 4.2.11 on 2024-05-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplist',
            name='task',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks_app.task'),
            preserve_default=False,
        ),
    ]
