# Generated by Django 4.2.11 on 2024-06-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0007_expense'),
        ('tasks_app', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplist',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoplist',
            name='category_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.categoryproject'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_app.task')),
            ],
        ),
    ]
