# Generated by Django 4.2.11 on 2024-06-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0007_taskep_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
